name: Bjorn Davidsson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40153
title: Photos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020305'
    - '#152a3d'
    - '#c5bc9d'
    - '#ffffff'
    - '#a37039'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
